export const NIGERIAN_EDUCATION_LEVELS = [
  { label: 'College', value: 'college' },
  { label: "Bachelor's Degree (BSc/BA)", value: 'bsc' },
  { label: "Master's Degree (MSc/MA)", value: 'masters' },
  { label: 'Doctorate (PhD)', value: 'phd' },
  { label: 'Doctorate (PhD)', value: 'doctorate' },
  { label: 'Professor', value: 'professor' },
];

export const NIGERIAN_STATES = [
  { label: 'Abia', value: 'abia' },
  { label: 'Adamawa', value: 'adamawa' },
  { label: 'Akwa Ibom', value: 'akwa_ibom' },
  { label: 'Anambra', value: 'anambra' },
  { label: 'Bauchi', value: 'bauchi' },
  { label: 'Bayelsa', value: 'bayelsa' },
  { label: 'Benue', value: 'benue' },
  { label: 'Borno', value: 'borno' },
  { label: 'Cross River', value: 'cross_river' },
  { label: 'Delta', value: 'delta' },
  { label: 'Ebonyi', value: 'ebonyi' },
  { label: 'Edo', value: 'edo' },
  { label: 'Ekiti', value: 'ekiti' },
  { label: 'Enugu', value: 'enugu' },
  { label: 'Abuja (FCT)', value: 'abuja' },
  { label: 'Gombe', value: 'gombe' },
  { label: 'Imo', value: 'imo' },
  { label: 'Jigawa', value: 'jigawa' },
  { label: 'Kaduna', value: 'kaduna' },
  { label: 'Kano', value: 'kano' },
  { label: 'Katsina', value: 'katsina' },
  { label: 'Kebbi', value: 'kebbi' },
  { label: 'Kogi', value: 'kogi' },
  { label: 'Kwara', value: 'kwara' },
  { label: 'Lagos', value: 'lagos' },
  { label: 'Nasarawa', value: 'nasarawa' },
  { label: 'Niger', value: 'niger' },
  { label: 'Ogun', value: 'ogun' },
  { label: 'Ondo', value: 'ondo' },
  { label: 'Osun', value: 'osun' },
  { label: 'Oyo', value: 'oyo' },
  { label: 'Plateau', value: 'plateau' },
  { label: 'Rivers', value: 'rivers' },
  { label: 'Sokoto', value: 'sokoto' },
  { label: 'Taraba', value: 'taraba' },
  { label: 'Yobe', value: 'yobe' },
  { label: 'Zamfara', value: 'zamfara' },
];

export const NIGERIAN_BUSINESS_TYPES = [
  { label: 'Sole Proprietorship', value: 'sole_proprietorship' },
  { label: 'Partnership', value: 'partnership' },
  { label: 'Corporation', value: 'corporation' },
  { label: 'Limited Liability Company', value: 'limited_liability_company' },
  { label: 'Cooperative', value: 'cooperative' },
  { label: 'Non-Profit Organization', value: 'non_profit_organization' },
  { label: 'Other', value: 'other' },
];

export const NIGERIAN_BUSINESS_INDUSTRIES = [
  { label: 'Agriculture/Forestry', value: 'agriculture' },
  { label: 'Building/Construction/Real Estate development', value: 'construction' },
  { label: 'Transportation/Storage', value: 'transportation' },
  { label: 'Government/MDAs', value: 'government' },
  { label: 'Manufacturing/Producing', value: 'manufacturing' },
  { label: 'Mining/Quarrying/Mineral business', value: 'mining' },
  { label: 'Consumer durables/household items', value: 'consumer_goods' },
  { label: 'General Commerce/Traders/Importers/Exporters', value: 'general_commerce' },
  { label: 'Professionals - Journalists/Lawyers/Accountants etc.', value: 'professionals' },
  { label: 'Financial Services/banking/Insurance/capital Markets', value: 'finance' },
  { label: 'Communications/Tele-communications', value: 'communication' },
  { label: 'Hospitals/Healthcare/Pharmaceuticals', value: 'healthcare' },
  { label: 'Hotels/Hospitality/Leisure', value: 'hospitality' },
  { label: 'Automobiles/Automobile Products', value: 'automobiles' },
  { label: 'Education/Schools', value: 'education' },
  { label: 'Oil', value: 'oil' },
];

export const NIGERIAN_BUSINESS_EMPLOYMENT_TYPES = [
  { label: 'Permanent', value: 'permanent' },
  { label: 'Part-Time', value: 'part_time' },
  { label: 'Contract', value: 'contract' },
  { label: 'Freelance', value: 'freelance' },
  { label: 'Self-Employed', value: 'self_employed' },
  { label: 'Unemployed', value: 'unemployed' },
];

export const NIGERIAN_LGA_BY_STATE = {
  abia: [
    { label: 'Aba North', value: 'aba_north' },
    { label: 'Aba South', value: 'aba_south' },
    { label: 'Arochukwu', value: 'arochukwu' },
    { label: 'Bende', value: 'bende' },
    { label: 'Ikwuano', value: 'ikwuano' },
    { label: 'Isiala Ngwa North', value: 'isiala_ngwa_north' },
    { label: 'Isiala Ngwa South', value: 'isiala_ngwa_south' },
    { label: 'Isuikwuato', value: 'isuikwuato' },
    { label: 'Obi Ngwa', value: 'obi_ngwa' },
    { label: 'Ohafia', value: 'ohafia' },
    { label: 'Osisioma', value: 'osisioma' },
    { label: 'Ugwunagbo', value: 'ugwunagbo' },
    { label: 'Ukwa East', value: 'ukwa_east' },
    { label: 'Ukwa West', value: 'ukwa_west' },
    { label: 'Umuahia North', value: 'umuahia_north' },
    { label: 'Umuahia South', value: 'umuahia_south' },
    { label: 'Umu Nneochi', value: 'umu_nneochi' },
  ],
  adamawa: [
    { label: 'Demsa', value: 'demsa' },
    { label: 'Fufore', value: 'fufore' },
    { label: 'Ganye', value: 'ganye' },
    { label: 'Girei', value: 'girei' },
    { label: 'Gombi', value: 'gombi' },
    { label: 'Guyuk', value: 'guyuk' },
    { label: 'Hong', value: 'hong' },
    { label: 'Jada', value: 'jada' },
    { label: 'Lamurde', value: 'lamurde' },
    { label: 'Madagali', value: 'madagali' },
    { label: 'Maiha', value: 'maiha' },
    { label: 'Mayo Belwa', value: 'mayo_belwa' },
    { label: 'Michika', value: 'michika' },
    { label: 'Mubi North', value: 'mubi_north' },
    { label: 'Mubi South', value: 'mubi_south' },
    { label: 'Numan', value: 'numan' },
    { label: 'Shelleng', value: 'shelleng' },
    { label: 'Song', value: 'song' },
    { label: 'Toungo', value: 'toungo' },
    { label: 'Yola North', value: 'yola_north' },
    { label: 'Yola South', value: 'yola_south' },
  ],
  lagos: [
    { label: 'Agege', value: 'agege' },
    { label: 'Ajeromi-Ifelodun', value: 'ajeromi_ifelodun' },
    { label: 'Alimosho', value: 'alimosho' },
    { label: 'Amuwo-Odofin', value: 'amuwo_odofin' },
    { label: 'Apapa', value: 'apapa' },
    { label: 'Badagry', value: 'badagry' },
    { label: 'Epe', value: 'epe' },
    { label: 'Eti Osa', value: 'eti_osa' },
    { label: 'Ibeju-Lekki', value: 'ibeju_lekki' },
    { label: 'Ifako-Ijaiye', value: 'ifako_ijaiye' },
    { label: 'Ikeja', value: 'ikeja' },
    { label: 'Ikorodu', value: 'ikorodu' },
    { label: 'Kosofe', value: 'kosofe' },
    { label: 'Lagos Island', value: 'lagos_island' },
    { label: 'Lagos Mainland', value: 'lagos_mainland' },
    { label: 'Mushin', value: 'mushin' },
    { label: 'Ojo', value: 'ojo' },
    { label: 'Oshodi-Isolo', value: 'oshodi_isolo' },
    { label: 'Shomolu', value: 'shomolu' },
    { label: 'Surulere', value: 'surulere' },
  ],
  abuja: [
    { label: 'Abaji', value: 'abaji' },
    { label: 'Bwari', value: 'bwari' },
    { label: 'Gwagwalada', value: 'gwagwalada' },
    { label: 'Kuje', value: 'kuje' },
    { label: 'Kwali', value: 'kwali' },
    { label: 'Municipal Area Council', value: 'municipal_area_council' },
  ],
  kano: [
    { label: 'Ajingi', value: 'ajingi' },
    { label: 'Albasu', value: 'albasu' },
    { label: 'Bagwai', value: 'bagwai' },
    { label: 'Bebeji', value: 'bebeji' },
    { label: 'Bichi', value: 'bichi' },
    { label: 'Bunkure', value: 'bunkure' },
    { label: 'Dala', value: 'dala' },
    { label: 'Dambatta', value: 'dambatta' },
    { label: 'Dawakin Kudu', value: 'dawakin_kudu' },
    { label: 'Dawakin Tofa', value: 'dawakin_tofa' },
    { label: 'Doguwa', value: 'doguwa' },
    { label: 'Fagge', value: 'fagge' },
    { label: 'Gabasawa', value: 'gabasawa' },
    { label: 'Garko', value: 'garko' },
    { label: 'Garun Mallam', value: 'garun_mallam' },
    { label: 'Gaya', value: 'gaya' },
    { label: 'Gezawa', value: 'gezawa' },
    { label: 'Gwale', value: 'gwale' },
    { label: 'Gwarzo', value: 'gwarzo' },
    { label: 'Kabo', value: 'kabo' },
    { label: 'Kano Municipal', value: 'kano_municipal' },
    { label: 'Karaye', value: 'karaye' },
    { label: 'Kibiya', value: 'kibiya' },
    { label: 'Kiru', value: 'kiru' },
    { label: 'Kumbotso', value: 'kumbotso' },
    { label: 'Kunchi', value: 'kunchi' },
    { label: 'Kura', value: 'kura' },
    { label: 'Madobi', value: 'madobi' },
    { label: 'Makoda', value: 'makoda' },
    { label: 'Minjibir', value: 'minjibir' },
    { label: 'Nasarawa', value: 'nasarawa' },
    { label: 'Rano', value: 'rano' },
    { label: 'Rimin Gado', value: 'rimin_gado' },
    { label: 'Rogo', value: 'rogo' },
    { label: 'Shanono', value: 'shanono' },
    { label: 'Sumaila', value: 'sumaila' },
    { label: 'Takai', value: 'takai' },
    { label: 'Tarauni', value: 'tarauni' },
    { label: 'Tofa', value: 'tofa' },
    { label: 'Tsanyawa', value: 'tsanyawa' },
    { label: 'Tudun Wada', value: 'tudun_wada' },
    { label: 'Ungogo', value: 'ungogo' },
    { label: 'Warawa', value: 'warawa' },
    { label: 'Wudil', value: 'wudil' },
  ],
  rivers: [
    { label: 'Abua/Odual', value: 'abua_odual' },
    { label: 'Ahoada East', value: 'ahoada_east' },
    { label: 'Ahoada West', value: 'ahoada_west' },
    { label: 'Akuku-Toru', value: 'akuku_toru' },
    { label: 'Andoni', value: 'andoni' },
    { label: 'Asari-Toru', value: 'asari_toru' },
    { label: 'Bonny', value: 'bonny' },
    { label: 'Degema', value: 'degema' },
    { label: 'Eleme', value: 'eleme' },
    { label: 'Emuoha', value: 'emuoha' },
    { label: 'Etche', value: 'etche' },
    { label: 'Gokana', value: 'gokana' },
    { label: 'Ikwerre', value: 'ikwerre' },
    { label: 'Khana', value: 'khana' },
    { label: 'Obio/Akpor', value: 'obio_akpor' },
    { label: 'Ogba/Egbema/Ndoni', value: 'ogba_egbema_ndoni' },
    { label: 'Ogu/Bolo', value: 'ogu_bolo' },
    { label: 'Okrika', value: 'okrika' },
    { label: 'Omuma', value: 'omuma' },
    { label: 'Opobo/Nkoro', value: 'opobo_nkoro' },
    { label: 'Oyigbo', value: 'oyigbo' },
    { label: 'Port Harcourt', value: 'port_harcourt' },
    { label: 'Tai', value: 'tai' },
  ],
  akwa_ibom: [
    { label: 'Abak', value: 'abak' },
    { label: 'Eastern Obolo', value: 'eastern_obolo' },
    { label: 'Eket', value: 'eket' },
    { label: 'Esit Eket', value: 'esit_eket' },
    { label: 'Essien Udim', value: 'essien_udim' },
    { label: 'Etim Ekpo', value: 'etim_ekpo' },
    { label: 'Etinan', value: 'etinan' },
    { label: 'Ibeno', value: 'ibeno' },
    { label: 'Ibesikpo Asutan', value: 'ibesikpo_asutan' },
    { label: 'Ibiono Ibom', value: 'ibiono_ibom' },
    { label: 'Ika', value: 'ika' },
    { label: 'Ikono', value: 'ikono' },
    { label: 'Ikot Abasi', value: 'ikot_abasi' },
    { label: 'Ikot Ekpene', value: 'ikot_ekpene' },
    { label: 'Ini', value: 'ini' },
    { label: 'Itu', value: 'itu' },
    { label: 'Mbo', value: 'mbo' },
    { label: 'Mkpat Enin', value: 'mkpat_enin' },
    { label: 'Nsit Atai', value: 'nsit_atai' },
    { label: 'Nsit Ibom', value: 'nsit_ibom' },
    { label: 'Nsit Ubium', value: 'nsit_ubium' },
    { label: 'Obot Akara', value: 'obot_akara' },
    { label: 'Okobo', value: 'okobo' },
    { label: 'Onna', value: 'onna' },
    { label: 'Oron', value: 'oron' },
    { label: 'Oruk Anam', value: 'oruk_anam' },
    { label: 'Udung Uko', value: 'udung_uko' },
    { label: 'Ukanafun', value: 'ukanafun' },
    { label: 'Uruan', value: 'uruan' },
    { label: 'Urue-Offong/Oruko', value: 'urue_offong_oruko' },
    { label: 'Uyo', value: 'uyo' }
  ],
  anambra: [
    { label: 'Aguata', value: 'aguata' },
    { label: 'Anambra East', value: 'anambra_east' },
    { label: 'Anambra West', value: 'anambra_west' },
    { label: 'Anaocha', value: 'anaocha' },
    { label: 'Awka North', value: 'awka_north' },
    { label: 'Awka South', value: 'awka_south' },
    { label: 'Ayamelum', value: 'ayamelum' },
    { label: 'Dunukofia', value: 'dunukofia' },
    { label: 'Ekwusigo', value: 'ekwusigo' },
    { label: 'Idemili North', value: 'idemili_north' },
    { label: 'Idemili South', value: 'idemili_south' },
    { label: 'Ihiala', value: 'ihiala' },
    { label: 'Njikoka', value: 'njikoka' },
    { label: 'Nnewi North', value: 'nnewi_north' },
    { label: 'Nnewi South', value: 'nnewi_south' },
    { label: 'Ogbaru', value: 'ogbaru' },
    { label: 'Onitsha North', value: 'onitsha_north' },
    { label: 'Onitsha South', value: 'onitsha_south' },
    { label: 'Orumba North', value: 'orumba_north' },
    { label: 'Orumba South', value: 'orumba_south' },
    { label: 'Oyi', value: 'oyi' }
  ],
  bauchi: [
    { label: 'Alkaleri', value: 'alkaleri' },
    { label: 'Bauchi', value: 'bauchi' },
    { label: 'Bogoro', value: 'bogoro' },
    { label: 'Damban', value: 'damban' },
    { label: 'Darazo', value: 'darazo' },
    { label: 'Dass', value: 'dass' },
    { label: 'Gamawa', value: 'gamawa' },
    { label: 'Ganjuwa', value: 'ganjuwa' },
    { label: 'Giade', value: 'giade' },
    { label: 'Jama\'are', value: 'jamaare' },
    { label: 'Katagum', value: 'katagum' },
    { label: 'Kirfi', value: 'kirfi' },
    { label: 'Misau', value: 'misau' },
    { label: 'Ningi', value: 'ningi' },
    { label: 'Shira', value: 'shira' },
    { label: 'Tafawa Balewa', value: 'tafawa_balewa' },
    { label: 'Itas/Gadau', value: 'itas_gadau' },
    { label: 'Toro', value: 'toro' },
    { label: 'Warji', value: 'warji' },
    { label: 'Zaki', value: 'zaki' }
  ],
  bayelsa: [
    { label: 'Brass', value: 'brass' },
    { label: 'Ekeremor', value: 'ekeremor' },
    { label: 'Kolokuma/Opokuma', value: 'kolokuma_opokuma' },
    { label: 'Nembe', value: 'nembe' },
    { label: 'Ogbia', value: 'ogbia' },
    { label: 'Sagbama', value: 'sagbama' },
    { label: 'Southern Ijaw', value: 'southern_ijaw' },
    { label: 'Yenagoa', value: 'yenagoa' }
  ],
  benue: [
    { label: 'Ado', value: 'ado' },
    { label: 'Agatu', value: 'agatu' },
    { label: 'Apa', value: 'apa' },
    { label: 'Buruku', value: 'buruku' },
    { label: 'Gboko', value: 'gboko' },
    { label: 'Guma', value: 'guma' },
    { label: 'Gwer East', value: 'gwer_east' },
    { label: 'Gwer West', value: 'gwer_west' },
    { label: 'Katsina-Ala', value: 'katsina_ala' },
    { label: 'Konshisha', value: 'konshisha' },
    { label: 'Kwande', value: 'kwande' },
    { label: 'Logo', value: 'logo' },
    { label: 'Makurdi', value: 'makurdi' },
    { label: 'Obi', value: 'obi' },
    { label: 'Ogbadibo', value: 'ogbadibo' },
    { label: 'Ohimini', value: 'ohimini' },
    { label: 'Oju', value: 'oju' },
    { label: 'Okpokwu', value: 'okpokwu' },
    { label: 'Oturkpo', value: 'oturkpo' },
    { label: 'Tarka', value: 'tarka' },
    { label: 'Ukum', value: 'ukum' },
    { label: 'Ushongo', value: 'ushongo' },
    { label: 'Vandeikya', value: 'vandeikya' }
  ],
  borno: [
    { label: 'Abadam', value: 'abadam' },
    { label: 'Askira/Uba', value: 'askira_uba' },
    { label: 'Bama', value: 'bama' },
    { label: 'Bayo', value: 'bayo' },
    { label: 'Biu', value: 'biu' },
    { label: 'Chibok', value: 'chibok' },
    { label: 'Damboa', value: 'damboa' },
    { label: 'Dikwa', value: 'dikwa' },
    { label: 'Gubio', value: 'gubio' },
    { label: 'Guzamala', value: 'guzamala' },
    { label: 'Gwoza', value: 'gwoza' },
    { label: 'Hawul', value: 'hawul' },
    { label: 'Jere', value: 'jere' },
    { label: 'Kaga', value: 'kaga' },
    { label: 'Kala/Balge', value: 'kala_balge' },
    { label: 'Konduga', value: 'konduga' },
    { label: 'Kukawa', value: 'kukawa' },
    { label: 'Kwaya Kusar', value: 'kwaya_kusar' },
    { label: 'Mafa', value: 'mafa' },
    { label: 'Magumeri', value: 'magumeri' },
    { label: 'Maiduguri', value: 'maiduguri' },
    { label: 'Marte', value: 'marte' },
    { label: 'Mobbar', value: 'mobbar' },
    { label: 'Monguno', value: 'monguno' },
    { label: 'Ngala', value: 'ngala' },
    { label: 'Nganzai', value: 'nganzai' },
    { label: 'Shani', value: 'shani' }
  ],
  cross_river: [
    { label: 'Abi', value: 'abi' },
    { label: 'Akamkpa', value: 'akamkpa' },
    { label: 'Akpabuyo', value: 'akpabuyo' },
    { label: 'Bakassi', value: 'bakassi' },
    { label: 'Bekwarra', value: 'bekwarra' },
    { label: 'Biase', value: 'biase' },
    { label: 'Boki', value: 'boki' },
    { label: 'Calabar Municipal', value: 'calabar_municipal' },
    { label: 'Calabar South', value: 'calabar_south' },
    { label: 'Etung', value: 'etung' },
    { label: 'Ikom', value: 'ikom' },
    { label: 'Obanliku', value: 'obanliku' },
    { label: 'Obubra', value: 'obubra' },
    { label: 'Obudu', value: 'obudu' },
    { label: 'Odukpani', value: 'odukpani' },
    { label: 'Ogoja', value: 'ogoja' },
    { label: 'Yakuur', value: 'yakuur' },
    { label: 'Yala', value: 'yala' }
  ],
  delta: [
    { label: 'Aniocha North', value: 'aniocha_north' },
    { label: 'Aniocha South', value: 'aniocha_south' },
    { label: 'Bomadi', value: 'bomadi' },
    { label: 'Burutu', value: 'burutu' },
    { label: 'Ethiope East', value: 'ethiope_east' },
    { label: 'Ethiope West', value: 'ethiope_west' },
    { label: 'Ika North East', value: 'ika_north_east' },
    { label: 'Ika South', value: 'ika_south' },
    { label: 'Isoko North', value: 'isoko_north' },
    { label: 'Isoko South', value: 'isoko_south' },
    { label: 'Ndokwa East', value: 'ndokwa_east' },
    { label: 'Ndokwa West', value: 'ndokwa_west' },
    { label: 'Okpe', value: 'okpe' },
    { label: 'Oshimili North', value: 'oshimili_north' },
    { label: 'Oshimili South', value: 'oshimili_south' },
    { label: 'Patani', value: 'patani' },
    { label: 'Sapele', value: 'sapele' },
    { label: 'Udu', value: 'udu' },
    { label: 'Ughelli North', value: 'ughelli_north' },
    { label: 'Ughelli South', value: 'ughelli_south' },
    { label: 'Ukwuani', value: 'ukwuani' },
    { label: 'Uvwie', value: 'uvwie' },
    { label: 'Warri North', value: 'warri_north' },
    { label: 'Warri South', value: 'warri_south' },
    { label: 'Warri South West', value: 'warri_south_west' }
  ],
  ebonyi: [
    { label: 'Abakaliki', value: 'abakaliki' },
    { label: 'Afikpo North', value: 'afikpo_north' },
    { label: 'Afikpo South', value: 'afikpo_south' },
    { label: 'Ebonyi', value: 'ebonyi' },
    { label: 'Ezza North', value: 'ezza_north' },
    { label: 'Ezza South', value: 'ezza_south' },
    { label: 'Ikwo', value: 'ikwo' },
    { label: 'Ishielu', value: 'ishielu' },
    { label: 'Ivo', value: 'ivo' },
    { label: 'Izzi', value: 'izzi' },
    { label: 'Ohaozara', value: 'ohaozara' },
    { label: 'Ohaukwu', value: 'ohaukwu' },
    { label: 'Onicha', value: 'onicha' }
  ],
  edo: [
    { label: 'Akoko-Edo', value: 'akoko_edo' },
    { label: 'Egor', value: 'egor' },
    { label: 'Esan Central', value: 'esan_central' },
    { label: 'Esan North-East', value: 'esan_north_east' },
    { label: 'Esan South-East', value: 'esan_south_east' },
    { label: 'Esan West', value: 'esan_west' },
    { label: 'Etsako Central', value: 'etsako_central' },
    { label: 'Etsako East', value: 'etsako_east' },
    { label: 'Etsako West', value: 'etsako_west' },
    { label: 'Igueben', value: 'igueben' },
    { label: 'Ikpoba Okha', value: 'ikpoba_okha' },
    { label: 'Oredo', value: 'oredo' },
    { label: 'Orhionmwon', value: 'orhionmwon' },
    { label: 'Ovia North-East', value: 'ovia_north_east' },
    { label: 'Ovia South-West', value: 'ovia_south_west' },
    { label: 'Owan East', value: 'owan_east' },
    { label: 'Owan West', value: 'owan_west' },
    { label: 'Uhunmwonde', value: 'uhunmwonde' }
  ],
  ekiti: [
    { label: 'Ado Ekiti', value: 'ado_ekiti' },
    { label: 'Efon', value: 'efon' },
    { label: 'Ekiti East', value: 'ekiti_east' },
    { label: 'Ekiti South-West', value: 'ekiti_south_west' },
    { label: 'Ekiti West', value: 'ekiti_west' },
    { label: 'Emure', value: 'emure' },
    { label: 'Gbonyin', value: 'gbonyin' },
    { label: 'Ido Osi', value: 'ido_osi' },
    { label: 'Ijero', value: 'ijero' },
    { label: 'Ikere', value: 'ikere' },
    { label: 'Ikole', value: 'ikole' },
    { label: 'Ilejemeje', value: 'ilejemeje' },
    { label: 'Irepodun/Ifelodun', value: 'irepodun_ifelodun' },
    { label: 'Ise/Orun', value: 'ise_orun' },
    { label: 'Moba', value: 'moba' },
    { label: 'Oye', value: 'oye' }
  ],
  enugu: [
    { label: 'Aninri', value: 'aninri' },
    { label: 'Awgu', value: 'awgu' },
    { label: 'Enugu East', value: 'enugu_east' },
    { label: 'Enugu North', value: 'enugu_north' },
    { label: 'Enugu South', value: 'enugu_south' },
    { label: 'Ezeagu', value: 'ezeagu' },
    { label: 'Igbo Etiti', value: 'igbo_etiti' },
    { label: 'Igbo Eze North', value: 'igbo_eze_north' },
    { label: 'Igbo Eze South', value: 'igbo_eze_south' },
    { label: 'Isi Uzo', value: 'isi_uzo' },
    { label: 'Nkanu East', value: 'nkanu_east' },
    { label: 'Nkanu West', value: 'nkanu_west' },
    { label: 'Nsukka', value: 'nsukka' },
    { label: 'Oji River', value: 'oji_river' },
    { label: 'Udenu', value: 'udenu' },
    { label: 'Udi', value: 'udi' },
    { label: 'Uzo Uwani', value: 'uzo_uwani' }
  ],
  gombe: [
    { label: 'Akko', value: 'akko' },
    { label: 'Balanga', value: 'balanga' },
    { label: 'Billiri', value: 'billiri' },
    { label: 'Dukku', value: 'dukku' },
    { label: 'Funakaye', value: 'funakaye' },
    { label: 'Gombe', value: 'gombe' },
    { label: 'Kaltungo', value: 'kaltungo' },
    { label: 'Kwami', value: 'kwami' },
    { label: 'Nafada', value: 'nafada' },
    { label: 'Shongom', value: 'shongom' },
    { label: 'Yamaltu/Deba', value: 'yamaltu_deba' }
  ],
  imo: [
    { label: 'Aboh Mbaise', value: 'aboh_mbaise' },
    { label: 'Ahiazu Mbaise', value: 'ahiazu_mbaise' },
    { label: 'Ehime Mbano', value: 'ehime_mbano' },
    { label: 'Ezinihitte', value: 'ezinihitte' },
    { label: 'Ideato North', value: 'ideato_north' },
    { label: 'Ideato South', value: 'ideato_south' },
    { label: 'Ihitte/Uboma', value: 'ihitte_uboma' },
    { label: 'Ikeduru', value: 'ikeduru' },
    { label: 'Isiala Mbano', value: 'isiala_mbano' },
    { label: 'Isu', value: 'isu' },
    { label: 'Mbaitoli', value: 'mbaitoli' },
    { label: 'Ngor Okpala', value: 'ngor_okpala' },
    { label: 'Njaba', value: 'njaba' },
    { label: 'Nkwerre', value: 'nkwerre' },
    { label: 'Nwangele', value: 'nwangele' },
    { label: 'Obowo', value: 'obowo' },
    { label: 'Oguta', value: 'oguta' },
    { label: 'Ohaji/Egbema', value: 'ohaji_egbema' },
    { label: 'Okigwe', value: 'okigwe' },
    { label: 'Orlu', value: 'orlu' },
    { label: 'Orsu', value: 'orsu' },
    { label: 'Oru East', value: 'oru_east' },
    { label: 'Oru West', value: 'oru_west' },
    { label: 'Owerri Municipal', value: 'owerri_municipal' },
    { label: 'Owerri North', value: 'owerri_north' },
    { label: 'Owerri West', value: 'owerri_west' },
    { label: 'Unuimo', value: 'unuimo' }
  ],
  jigawa: [
    { label: 'Auyo', value: 'auyo' },
    { label: 'Babura', value: 'babura' },
    { label: 'Biriniwa', value: 'biriniwa' },
    { label: 'Birnin Kudu', value: 'birnin_kudu' },
    { label: 'Buji', value: 'buji' },
    { label: 'Dutse', value: 'dutse' },
    { label: 'Gagarawa', value: 'gagarawa' },
    { label: 'Garki', value: 'garki' },
    { label: 'Gumel', value: 'gumel' },
    { label: 'Guri', value: 'guri' },
    { label: 'Gwaram', value: 'gwaram' },
    { label: 'Gwiwa', value: 'gwiwa' },
    { label: 'Hadejia', value: 'hadejia' },
    { label: 'Jahun', value: 'jahun' },
    { label: 'Kafin Hausa', value: 'kafin_hausa' },
    { label: 'Kazaure', value: 'kazaure' },
    { label: 'Kiri Kasama', value: 'kiri_kasama' },
    { label: 'Kiyawa', value: 'kiyawa' },
    { label: 'Maigatari', value: 'maigatari' },
    { label: 'Malam Madori', value: 'malam_madori' },
    { label: 'Miga', value: 'miga' },
    { label: 'Ringim', value: 'ringim' },
    { label: 'Roni', value: 'roni' },
    { label: 'Sule Tankarkar', value: 'sule_tankarkar' },
    { label: 'Taura', value: 'taura' },
    { label: 'Yankwashi', value: 'yankwashi' }
  ],
  kaduna: [
    { label: 'Birnin Gwari', value: 'birnin_gwari' },
    { label: 'Chikun', value: 'chikun' },
    { label: 'Giwa', value: 'giwa' },
    { label: 'Igabi', value: 'igabi' },
    { label: 'Ikara', value: 'ikara' },
    { label: 'Jaba', value: 'jaba' },
    { label: 'Jema\'a', value: 'jemaa' },
    { label: 'Kachia', value: 'kachia' },
    { label: 'Kaduna North', value: 'kaduna_north' },
    { label: 'Kaduna South', value: 'kaduna_south' },
    { label: 'Kagarko', value: 'kagarko' },
    { label: 'Kajuru', value: 'kajuru' },
    { label: 'Kaura', value: 'kaura' },
    { label: 'Kauru', value: 'kauru' },
    { label: 'Kubau', value: 'kubau' },
    { label: 'Kudan', value: 'kudan' },
    { label: 'Lere', value: 'lere' },
    { label: 'Makarfi', value: 'makarfi' },
    { label: 'Sabon Gari', value: 'sabon_gari' },
    { label: 'Sanga', value: 'sanga' },
    { label: 'Soba', value: 'soba' },
    { label: 'Zangon Kataf', value: 'zangon_kataf' },
    { label: 'Zaria', value: 'zaria' }
  ],
  katsina: [
    { label: 'Bakori', value: 'bakori' },
    { label: 'Batagarawa', value: 'batagarawa' },
    { label: 'Batsari', value: 'batsari' },
    { label: 'Baure', value: 'baure' },
    { label: 'Bindawa', value: 'bindawa' },
    { label: 'Charanchi', value: 'charanchi' },
    { label: 'Dan Musa', value: 'dan_musa' },
    { label: 'Dandume', value: 'dandume' },
    { label: 'Danja', value: 'danja' },
    { label: 'Daura', value: 'daura' },
    { label: 'Dutsi', value: 'dutsi' },
    { label: 'Dutsin Ma', value: 'dutsin_ma' },
    { label: 'Faskari', value: 'faskari' },
    { label: 'Funtua', value: 'funtua' },
    { label: 'Ingawa', value: 'ingawa' },
    { label: 'Jibia', value: 'jibia' },
    { label: 'Kafur', value: 'kafur' },
    { label: 'Kaita', value: 'kaita' },
    { label: 'Kankara', value: 'kankara' },
    { label: 'Kankia', value: 'kankia' },
    { label: 'Katsina', value: 'katsina' },
    { label: 'Kurfi', value: 'kurfi' },
    { label: 'Kusada', value: 'kusada' },
    { label: 'Mai\'Adua', value: 'mai_adua' },
    { label: 'Malumfashi', value: 'malumfashi' },
    { label: 'Mani', value: 'mani' },
    { label: 'Mashi', value: 'mashi' },
    { label: 'Matazu', value: 'matazu' },
    { label: 'Musawa', value: 'musawa' },
    { label: 'Rimi', value: 'rimi' },
    { label: 'Sabuwa', value: 'sabuwa' },
    { label: 'Safana', value: 'safana' },
    { label: 'Sandamu', value: 'sandamu' },
    { label: 'Zango', value: 'zango' }
  ],
  kebbi: [
    { label: 'Aleiro', value: 'aleiro' },
    { label: 'Arewa Dandi', value: 'arewa_dandi' },
    { label: 'Argungu', value: 'argungu' },
    { label: 'Augie', value: 'augie' },
    { label: 'Bagudo', value: 'bagudo' },
    { label: 'Birnin Kebbi', value: 'birnin_kebbi' },
    { label: 'Bunza', value: 'bunza' },
    { label: 'Dandi', value: 'dandi' },
    { label: 'Fakai', value: 'fakai' },
    { label: 'Gwandu', value: 'gwandu' },
    { label: 'Jega', value: 'jega' },
    { label: 'Kalgo', value: 'kalgo' },
    { label: 'Koko/Besse', value: 'koko_besse' },
    { label: 'Maiyama', value: 'maiyama' },
    { label: 'Ngaski', value: 'ngaski' },
    { label: 'Sakaba', value: 'sakaba' },
    { label: 'Shanga', value: 'shanga' },
    { label: 'Suru', value: 'suru' },
    { label: 'Wasagu/Danko', value: 'wasagu_danko' },
    { label: 'Yauri', value: 'yauri' },
    { label: 'Zuru', value: 'zuru' }
  ],
  kogi: [
    { label: 'Adavi', value: 'adavi' },
    { label: 'Ajaokuta', value: 'ajaokuta' },
    { label: 'Ankpa', value: 'ankpa' },
    { label: 'Bassa', value: 'bassa' },
    { label: 'Dekina', value: 'dekina' },
    { label: 'Ibaji', value: 'ibaji' },
    { label: 'Idah', value: 'idah' },
    { label: 'Igalamela Odolu', value: 'igalamela_odolu' },
    { label: 'Ijumu', value: 'ijumu' },
    { label: 'Kabba/Bunu', value: 'kabba_bunu' },
    { label: 'Kogi', value: 'kogi' },
    { label: 'Lokoja', value: 'lokoja' },
    { label: 'Mopa Muro', value: 'mopa_muro' },
    { label: 'Ofu', value: 'ofu' },
    { label: 'Ogori/Magongo', value: 'ogori_magongo' },
    { label: 'Okehi', value: 'okehi' },
    { label: 'Okene', value: 'okene' },
    { label: 'Olamaboro', value: 'olamaboro' },
    { label: 'Omala', value: 'omala' },
    { label: 'Yagba East', value: 'yagba_east' },
    { label: 'Yagba West', value: 'yagba_west' }
  ],
  kwara: [
    { label: 'Asa', value: 'asa' },
    { label: 'Baruten', value: 'baruten' },
    { label: 'Edu', value: 'edu' },
    { label: 'Ekiti', value: 'ekiti' },
    { label: 'Ifelodun', value: 'ifelodun' },
    { label: 'Ilorin East', value: 'ilorin_east' },
    { label: 'Ilorin South', value: 'ilorin_south' },
    { label: 'Ilorin West', value: 'ilorin_west' },
    { label: 'Irepodun', value: 'irepodun' },
    { label: 'Isin', value: 'isin' },
    { label: 'Kaiama', value: 'kaiama' },
    { label: 'Moro', value: 'moro' },
    { label: 'Offa', value: 'offa' },
    { label: 'Oke Ero', value: 'oke_ero' },
    { label: 'Oyun', value: 'oyun' },
    { label: 'Pategi', value: 'pategi' }
  ],
  nasarawa: [
    { label: 'Akwanga', value: 'akwanga' },
    { label: 'Awe', value: 'awe' },
    { label: 'Doma', value: 'doma' },
    { label: 'Karu', value: 'karu' },
    { label: 'Keana', value: 'keana' },
    { label: 'Keffi', value: 'keffi' },
    { label: 'Kokona', value: 'kokona' },
    { label: 'Lafia', value: 'lafia' },
    { label: 'Nasarawa', value: 'nasarawa' },
    { label: 'Nasarawa Egon', value: 'nasarawa_egon' },
    { label: 'Obi', value: 'obi' },
    { label: 'Toto', value: 'toto' },
    { label: 'Wamba', value: 'wamba' }
  ],
  niger: [
    { label: 'Agaie', value: 'agaie' },
    { label: 'Agwara', value: 'agwara' },
    { label: 'Bida', value: 'bida' },
    { label: 'Borgu', value: 'borgu' },
    { label: 'Bosso', value: 'bosso' },
    { label: 'Chanchaga', value: 'chanchaga' },
    { label: 'Edati', value: 'edati' },
    { label: 'Gbako', value: 'gbako' },
    { label: 'Gurara', value: 'gurara' },
    { label: 'Katcha', value: 'katcha' },
    { label: 'Kontagora', value: 'kontagora' },
    { label: 'Lapai', value: 'lapai' },
    { label: 'Lavun', value: 'lavun' },
    { label: 'Magama', value: 'magama' },
    { label: 'Mariga', value: 'mariga' },
    { label: 'Mashegu', value: 'mashegu' },
    { label: 'Mokwa', value: 'mokwa' },
    { label: 'Munya', value: 'munya' },
    { label: 'Paikoro', value: 'paikoro' },
    { label: 'Rafi', value: 'rafi' },
    { label: 'Rijau', value: 'rijau' },
    { label: 'Shiroro', value: 'shiroro' },
    { label: 'Suleja', value: 'suleja' },
    { label: 'Tafa', value: 'tafa' },
    { label: 'Wushishi', value: 'wushishi' }
  ],
  ogun: [
    { label: 'Abeokuta North', value: 'abeokuta_north' },
    { label: 'Abeokuta South', value: 'abeokuta_south' },
    { label: 'Ado-Odo/Ota', value: 'ado_odo_ota' },
    { label: 'Egbado North', value: 'egbado_north' },
    { label: 'Egbado South', value: 'egbado_south' },
    { label: 'Ewekoro', value: 'ewekoro' },
    { label: 'Ifo', value: 'ifo' },
    { label: 'Ijebu East', value: 'ijebu_east' },
    { label: 'Ijebu North', value: 'ijebu_north' },
    { label: 'Ijebu North East', value: 'ijebu_north_east' },
    { label: 'Ijebu Ode', value: 'ijebu_ode' },
    { label: 'Ikenne', value: 'ikenne' },
    { label: 'Imeko Afon', value: 'imeko_afon' },
    { label: 'Ipokia', value: 'ipokia' },
    { label: 'Obafemi Owode', value: 'obafemi_owode' },
    { label: 'Odeda', value: 'odeda' },
    { label: 'Odogbolu', value: 'odogbolu' },
    { label: 'Ogun Waterside', value: 'ogun_waterside' },
    { label: 'Remo North', value: 'remo_north' },
    { label: 'Shagamu', value: 'shagamu' }
  ],
  ondo: [
    { label: 'Akoko North-East', value: 'akoko_north_east' },
    { label: 'Akoko North-West', value: 'akoko_north_west' },
    { label: 'Akoko South-East', value: 'akoko_south_east' },
    { label: 'Akoko South-West', value: 'akoko_south_west' },
    { label: 'Akure North', value: 'akure_north' },
    { label: 'Akure South', value: 'akure_south' },
    { label: 'Ese Odo', value: 'ese_odo' },
    { label: 'Idanre', value: 'idanre' },
    { label: 'Ifedore', value: 'ifedore' },
    { label: 'Ilaje', value: 'ilaje' },
    { label: 'Ile Oluji/Okeigbo', value: 'ile_oluji_okeigbo' },
    { label: 'Irele', value: 'irele' },
    { label: 'Odigbo', value: 'odigbo' },
    { label: 'Okitipupa', value: 'okitipupa' },
    { label: 'Ondo East', value: 'ondo_east' },
    { label: 'Ondo West', value: 'ondo_west' },
    { label: 'Ose', value: 'ose' },
    { label: 'Owo', value: 'owo' }
  ],
  osun: [
    { label: 'Aiyedaade', value: 'aiyedaade' },
    { label: 'Aiyedire', value: 'aiyedire' },
    { label: 'Atakunmosa East', value: 'atakunmosa_east' },
    { label: 'Atakunmosa West', value: 'atakunmosa_west' },
    { label: 'Boluwaduro', value: 'boluwaduro' },
    { label: 'Boripe', value: 'boripe' },
    { label: 'Ede North', value: 'ede_north' },
    { label: 'Ede South', value: 'ede_south' },
    { label: 'Egbedore', value: 'egbedore' },
    { label: 'Ejigbo', value: 'ejigbo' },
    { label: 'Ife Central', value: 'ife_central' },
    { label: 'Ife East', value: 'ife_east' },
    { label: 'Ife North', value: 'ife_north' },
    { label: 'Ife South', value: 'ife_south' },
    { label: 'Ifedayo', value: 'ifedayo' },
    { label: 'Ifelodun', value: 'ifelodun' },
    { label: 'Ila', value: 'ila' },
    { label: 'Ilesa East', value: 'ilesa_east' },
    { label: 'Ilesa West', value: 'ilesa_west' },
    { label: 'Irepodun', value: 'irepodun' },
    { label: 'Irewole', value: 'irewole' },
    { label: 'Isokan', value: 'isokan' },
    { label: 'Iwo', value: 'iwo' },
    { label: 'Obokun', value: 'obokun' },
    { label: 'Odo Otin', value: 'odo_otin' },
    { label: 'Ola Oluwa', value: 'ola_oluwa' },
    { label: 'Olorunda', value: 'olorunda' },
    { label: 'Oriade', value: 'oriade' },
    { label: 'Orolu', value: 'orolu' },
    { label: 'Osogbo', value: 'osogbo' }
  ],
  oyo: [
    { label: 'Afijio', value: 'afijio' },
    { label: 'Akinyele', value: 'akinyele' },
    { label: 'Atiba', value: 'atiba' },
    { label: 'Atisbo', value: 'atisbo' },
    { label: 'Egbeda', value: 'egbeda' },
    { label: 'Ibadan North', value: 'ibadan_north' },
    { label: 'Ibadan North-East', value: 'ibadan_north_east' },
    { label: 'Ibadan North-West', value: 'ibadan_north_west' },
    { label: 'Ibadan South-East', value: 'ibadan_south_east' },
    { label: 'Ibadan South-West', value: 'ibadan_south_west' },
    { label: 'Ibarapa Central', value: 'ibarapa_central' },
    { label: 'Ibarapa East', value: 'ibarapa_east' },
    { label: 'Ibarapa North', value: 'ibarapa_north' },
    { label: 'Ido', value: 'ido' },
    { label: 'Irepo', value: 'irepo' },
    { label: 'Iseyin', value: 'iseyin' },
    { label: 'Itesiwaju', value: 'itesiwaju' },
    { label: 'Iwajowa', value: 'iwajowa' },
    { label: 'Kajola', value: 'kajola' },
    { label: 'Lagelu', value: 'lagelu' },
    { label: 'Ogbomosho North', value: 'ogbomosho_north' },
    { label: 'Ogbomosho South', value: 'ogbomosho_south' },
    { label: 'Ogo Oluwa', value: 'ogo_oluwa' },
    { label: 'Olorunsogo', value: 'olorunsogo' },
    { label: 'Oluyole', value: 'oluyole' },
    { label: 'Ona Ara', value: 'ona_ara' },
    { label: 'Orelope', value: 'orelope' },
    { label: 'Ori Ire', value: 'ori_ire' },
    { label: 'Oyo', value: 'oyo' },
    { label: 'Oyo East', value: 'oyo_east' },
    { label: 'Saki East', value: 'saki_east' },
    { label: 'Saki West', value: 'saki_west' },
    { label: 'Surulere', value: 'surulere' }
  ],
  plateau: [
    { label: 'Barkin Ladi', value: 'barkin_ladi' },
    { label: 'Bassa', value: 'bassa' },
    { label: 'Bokkos', value: 'bokkos' },
    { label: 'Jos East', value: 'jos_east' },
    { label: 'Jos North', value: 'jos_north' },
    { label: 'Jos South', value: 'jos_south' },
    { label: 'Kanam', value: 'kanam' },
    { label: 'Kanke', value: 'kanke' },
    { label: 'Langtang North', value: 'langtang_north' },
    { label: 'Langtang South', value: 'langtang_south' },
    { label: 'Mangu', value: 'mangu' },
    { label: 'Mikang', value: 'mikang' },
    { label: 'Pankshin', value: 'pankshin' },
    { label: 'Qua\'an Pan', value: 'qua_an_pan' },
    { label: 'Riyom', value: 'riyom' },
    { label: 'Shendam', value: 'shendam' },
    { label: 'Wase', value: 'wase' }
  ],
  sokoto: [
    { label: 'Binji', value: 'binji' },
    { label: 'Bodinga', value: 'bodinga' },
    { label: 'Dange Shuni', value: 'dange_shuni' },
    { label: 'Gada', value: 'gada' },
    { label: 'Goronyo', value: 'goronyo' },
    { label: 'Gudu', value: 'gudu' },
    { label: 'Gwadabawa', value: 'gwadabawa' },
    { label: 'Illela', value: 'illela' },
    { label: 'Isa', value: 'isa' },
    { label: 'Kebbe', value: 'kebbe' },
    { label: 'Kware', value: 'kware' },
    { label: 'Rabah', value: 'rabah' },
    { label: 'Sabon Birni', value: 'sabon_birni' },
    { label: 'Shagari', value: 'shagari' },
    { label: 'Silame', value: 'silame' },
    { label: 'Sokoto North', value: 'sokoto_north' },
    { label: 'Sokoto South', value: 'sokoto_south' },
    { label: 'Tambuwal', value: 'tambuwal' },
    { label: 'Tangaza', value: 'tangaza' },
    { label: 'Tureta', value: 'tureta' },
    { label: 'Wamako', value: 'wamako' },
    { label: 'Wurno', value: 'wurno' },
    { label: 'Yabo', value: 'yabo' }
  ],
  taraba: [
    { label: 'Ardo Kola', value: 'ardo_kola' },
    { label: 'Bali', value: 'bali' },
    { label: 'Donga', value: 'donga' },
    { label: 'Gashaka', value: 'gashaka' },
    { label: 'Gassol', value: 'gassol' },
    { label: 'Ibi', value: 'ibi' },
    { label: 'Jalingo', value: 'jalingo' },
    { label: 'Karim Lamido', value: 'karim_lamido' },
    { label: 'Kumi', value: 'kumi' },
    { label: 'Lau', value: 'lau' },
    { label: 'Sardauna', value: 'sardauna' },
    { label: 'Takum', value: 'takum' },
    { label: 'Ussa', value: 'ussa' },
    { label: 'Wukari', value: 'wukari' },
    { label: 'Yorro', value: 'yorro' },
    { label: 'Zing', value: 'zing' }
  ],
  yobe: [
    { label: 'Bade', value: 'bade' },
    { label: 'Bursari', value: 'bursari' },
    { label: 'Damaturu', value: 'damaturu' },
    { label: 'Fika', value: 'fika' },
    { label: 'Fune', value: 'fune' },
    { label: 'Geidam', value: 'geidam' },
    { label: 'Gujba', value: 'gujba' },
    { label: 'Gulani', value: 'gulani' },
    { label: 'Jakusko', value: 'jakusko' },
    { label: 'Karasuwa', value: 'karasuwa' },
    { label: 'Machina', value: 'machina' },
    { label: 'Nangere', value: 'nangere' },
    { label: 'Nguru', value: 'nguru' },
    { label: 'Potiskum', value: 'potiskum' },
    { label: 'Tarmuwa', value: 'tarmuwa' },
    { label: 'Yunusari', value: 'yunusari' },
    { label: 'Yusufari', value: 'yusufari' }
  ],
  zamfara: [
    { label: 'Anka', value: 'anka' },
    { label: 'Bakura', value: 'bakura' },
    { label: 'Birnin Magaji/Kiyaw', value: 'birnin_magaji_kiyaw' },
    { label: 'Bukkuyum', value: 'bukkuyum' },
    { label: 'Bungudu', value: 'bungudu' },
    { label: 'Gummi', value: 'gummi' },
    { label: 'Gusau', value: 'gusau' },
    { label: 'Kaura Namoda', value: 'kaura_namoda' },
    { label: 'Maradun', value: 'maradun' },
    { label: 'Maru', value: 'maru' },
    { label: 'Shinkafi', value: 'shinkafi' },
    { label: 'Talata Mafara', value: 'talata_mafara' },
    { label: 'Chafe', value: 'chafe' },
    { label: 'Zurmi', value: 'zurmi' }
  ]
};

// Function to get LGAs for a state
export const getLGAsByState = (stateValue: string) => {
  return NIGERIAN_LGA_BY_STATE[stateValue as keyof typeof NIGERIAN_LGA_BY_STATE] || [];
};