export const NIGERIAN_EDUCATION_LEVELS = [
  { label: 'College', value: 'college' },
  { label: "Bachelor's Degree (BSc/BA)", value: 'bsc' },
  { label: "Master's Degree (MSc/MA)", value: 'masters' },
  { label: 'Doctorate (PhD)', value: 'phd' },
  { label: 'Doctorate (PhD)', value: 'doctorate' },
  { label: 'Professor', value: 'professor' },
];

export const NIGERIAN_STATES = [
  { label: 'Abia', value: 'abia' },
  { label: 'Adamawa', value: 'adamawa' },
  { label: 'Akwa Ibom', value: 'akwa_ibom' },
  { label: 'Anambra', value: 'anambra' },
  { label: 'Bauchi', value: 'bauchi' },
  { label: 'Bayelsa', value: 'bayelsa' },
  { label: 'Benue', value: 'benue' },
  { label: 'Borno', value: 'borno' },
  { label: 'Cross River', value: 'cross_river' },
  { label: 'Delta', value: 'delta' },
  { label: 'Ebonyi', value: 'ebonyi' },
  { label: 'Edo', value: 'edo' },
  { label: 'Ekiti', value: 'ekiti' },
  { label: 'Enugu', value: 'enugu' },
  { label: 'Abuja (FCT)', value: 'abuja' },
  { label: 'Gombe', value: 'gombe' },
  { label: 'Imo', value: 'imo' },
  { label: 'Jigawa', value: 'jigawa' },
  { label: 'Kaduna', value: 'kaduna' },
  { label: 'Kano', value: 'kano' },
  { label: 'Katsina', value: 'katsina' },
  { label: 'Kebbi', value: 'kebbi' },
  { label: 'Kogi', value: 'kogi' },
  { label: 'Kwara', value: 'kwara' },
  { label: 'Lagos', value: 'lagos' },
  { label: 'Nasarawa', value: 'nasarawa' },
  { label: 'Niger', value: 'niger' },
  { label: 'Ogun', value: 'ogun' },
  { label: 'Ondo', value: 'ondo' },
  { label: 'Osun', value: 'osun' },
  { label: 'Oyo', value: 'oyo' },
  { label: 'Plateau', value: 'plateau' },
  { label: 'Rivers', value: 'rivers' },
  { label: 'Sokoto', value: 'sokoto' },
  { label: 'Taraba', value: 'taraba' },
  { label: 'Yobe', value: 'yobe' },
  { label: 'Zamfara', value: 'zamfara' },
];

export const NIGERIAN_BUSINESS_TYPES = [
  { label: 'Sole Proprietorship', value: 'sole_proprietorship' },
  { label: 'Partnership', value: 'partnership' },
  { label: 'Corporation', value: 'corporation' },
  { label: 'Limited Liability Company', value: 'limited_liability_company' },
  { label: 'Cooperative', value: 'cooperative' },
  { label: 'Non-Profit Organization', value: 'non_profit_organization' },
  { label: 'Other', value: 'other' },
];

export const NIGERIAN_BUSINESS_INDUSTRIES = [
  { label: 'Agriculture', value: 'agriculture' },
  { label: 'Construction', value: 'construction' },
  { label: 'Education', value: 'education' },
  { label: 'Finance', value: 'finance' },
  { label: 'Healthcare', value: 'healthcare' },
  { label: 'Hospitality', value: 'hospitality' },
  { label: 'Information Technology', value: 'information_technology' },
  { label: 'Manufacturing', value: 'manufacturing' },
  { label: 'Real Estate', value: 'real_estate' },
  { label: 'Retail', value: 'retail' },
  { label: 'Transportation', value: 'transportation' },
  { label: 'Other', value: 'other' },
];
